spring:
  application:
    name: saga
  cloud:
    stream:
      bindings:
        fileRequestOut:
          destination: storage
          producer.headerMode: headers
          contentType: application/json
        dbRequestOut:
          destination: database
          producer.headerMode: headers
          contentType: application/json
        bcRequestOut:
          destination: blockchain
          producer.headerMode: headers
          contentType: application/json
        txnResponseIn:
          destination: saga
          contentType: application/json
          consumer.headerMode: headers
          group: saga-group
