spring:
  application:
    name: remote-services
  cloud:
    stream:
      bindings:
        fileRequestIn:
          destination: storage
          contentType: application/json
          consumer.headerMode: headers
          group: storage-group
        dbRequestIn:
          destination: database
          contentType: application/json
          consumer.headerMode: headers
          group: database-group
        bcRequestIn:
          destination: blockchain
          contentType: application/json
          consumer.headerMode: headers
          group: blockchain-group
        txnResponseOut:
          destination: saga
          producer.headerMode: headers
          contentType: application/json

# random number between 0 to max
# if random number falls between the lower and higher bound simulation assumes error in a txn
# delay to simulate number of seconds a txn takes to process a request
file:
  max: 10
  submit_lower_bound: 4
  submit_higher_bound: 7
  cancel_lower_bound: 1
  cancel_higher_bound: 9
  delay: 1
  timeout: 2

db:
  max: 10
  submit_lower_bound: 3
  submit_higher_bound: 5
  cancel_lower_bound: 3
  cancel_higher_bound: 5
  delay: 1
  timeout: 2

bc:
  max: 10
  submit_lower_bound: 4
  submit_higher_bound: 8
  cancel_lower_bound: 4
  cancel_higher_bound: 8
  delay: 2
  timeout: 3
